# Generated by Django 4.2.3 on 2024-04-16 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'permissions': (('can_manage_products', 'Can add and manage products'),), 'verbose_name_plural': 'products'},
        ),
    ]
