# Generated by Django 3.2.6 on 2024-03-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_auto_20240310_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompermission',
            name='codename',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='custompermission',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
